version: '3'
services:
  # PHP Service
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: api:latest
    container_name: lamo-api
    restart: unless-stopped
    tty: true
    volumes:
       - ./api/:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SERVICE_NAME: lamo-api
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - lamo-network

  # Nginx Service
  server:
    image: nginx:alpine
    container_name: lamo-server
    restart: unless-stopped
    tty: true
    volumes:
      - ./api/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lamo-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: lamo-db
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lamo
      MYSQL_ROOT_PASSWORD: w5DnjnFuyb9N39AW
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lamo-network

# Volumes
volumes:
  dbdata:
    driver: local

# Docker Networks
networks:
  lamo-network:
    driver: bridge
